version: '3.1'
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5444:5432
    environment:
      POSTGRES_PASSWORD: TEST
      POSTGRES_DB: mev
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
